export const dataSources = {
  "BC5-401": {
    className: "custom-node",
    businessCenter: "963.1567",
    uniqueId: "693",
    firstName: "Dila",
    lastName: "dds",
    title: "Director",
    leftTotal: 50,
    rightTotal: 500,
    children: [
      {
        className: "custom-node",
        businessCenter: "742.3562",
        uniqueId: "853",
        firstName: "SOKU",
        lastName: "...",
        title: "Assistant Head",
        leftTotal: 845,
        rightTotal: 951,

        children: [
          {
            className: "custom-node",
            businessCenter: "02.36",
            uniqueId: "582",

            firstName: "Reynolds",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 971,
            rightTotal: 142,
            children: [
              {
                className: "custom-node",
                uniqueId: "112",

                businessCenter: "632",
                firstName: "Matthews",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 55,
                rightTotal: 36,
                children: [
                  {
                    className: "custom-node",
                    businessCenter: "3233",
                    uniqueId: "93.36",

                    firstName: "Udana",
                    lastName: "Taylor",
                    title: "Assistant ",
                    leftTotal: 55,
                    rightTotal: 36,
                    children: [
                      {
                        className: "custom-node",
                        businessCenter: "78512",
                        uniqueId: "9874",

                        firstName: "Robinson",
                        lastName: "Taylor",
                        title: "Assistant ",
                        leftTotal: 55,
                        rightTotal: 36,
                        children: [
                          {
                            className: "custom-node",
                            businessCenter: "3694254.612",
                            uniqueId: "12589.221",

                            firstName: "Somy",
                            lastName: "Taylor",
                            title: "Assistant ",
                            leftTotal: 55,
                            rightTotal: 36,
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                className: "custom-node",
                businessCenter: "787888",
                uniqueId: "7893.3",
                firstName: "Jenny",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 55,
                rightTotal: 36,
              },
            ],
          },
          {
            className: "custom-node",
            businessCenter: "025810",
            uniqueId: "369.28",
            firstName: "Oliver",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
      {
        className: "custom-node",
        businessCenter: "93.15542",
        uniqueId: "0258.66",
        firstName: "Maku",
        lastName: "Taylor",
        title: "Assistant Head",
        leftTotal: 69,
        rightTotal: 7132,
        children: [
          {
            className: "custom-node",
            businessCenter: "125",
            uniqueId: "999",
            firstName: "Potterrs",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 48,
            rightTotal: 63,
          },
          {
            className: "custom-node",
            businessCenter: "965",
            uniqueId: "777",
            firstName: "Metters",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 48,
            rightTotal: 63,
            children: [
              {
                className: "custom-node",
                businessCenter: "369",
                uniqueId: "30.28",

                firstName: "Dominick",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 48,
                rightTotal: 63,
                children: [
                  {
                    className: "custom-node",
                    businessCenter: "425",
                    uniqueId: "458",

                    firstName: "Gred",
                    lastName: "Taylor",
                    title: "Assistant ",
                    leftTotal: 48,
                    rightTotal: 63,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },

  "BC4-401": {
    className: "custom-node",
    businessCenter: "9000",
    uniqueId: "852",
    firstName: "James",
    lastName: "Wilson",
    title: "Senior Manager",
    leftTotal: 60,
    rightTotal: 700,
    children: [
      {
        className: "custom-node",
        businessCenter: "500",
        uniqueId: "1150",
        firstName: "tedd",
        lastName: "pola",
        title: "Assistant Head",
        leftTotal: 30,
        rightTotal: 300,
        children: [
          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "1840",
            firstName: "Noah",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },

          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "3690",
            firstName: "dadfa",
            lastName: "dd",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
      {
        className: "custom-node",
        businessCenter: "500",
        uniqueId: "7778",
        firstName: "Noah",
        lastName: "Taylor",
        title: "Assistant Head",
        leftTotal: 30,
        rightTotal: 300,
        children: [
          {
            className: "custom-node",
            businessCenter: "854",
            uniqueId: "0025",
            firstName: "",
            lastName: "",
            title: "",
            leftTotal: 30,
            rightTotal: 300,
          },

          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "7803.1",
            firstName: "Noah",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
    ],
  },

  "BC3-401": {
    className: "custom-node",
    businessCenter: "9000",
    uniqueId: "993",
    firstName: "Jimne",
    lastName: "Wilson",
    title: "Senior Manager",
    leftTotal: 60,
    rightTotal: 700,
    children: [
      {
        className: "custom-node",
        businessCenter: "110",
        uniqueId: "147",
        firstName: "Kimne",
        lastName: "pola",
        title: "Assistant Head",
        leftTotal: 30,
        rightTotal: 300,
        children: [
          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "9630",
            firstName: "Noah",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },

          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "7852",
            firstName: "dadfa",
            lastName: "dd",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
      {
        className: "custom-node",
        businessCenter: "500",
        uniqueId: "8888",
        firstName: "Noah",
        lastName: "Taylor",
        title: "Assistant Head",
        leftTotal: 30,
        rightTotal: 300,
        children: [
          {
            className: "custom-node",
            businessCenter: "854",
            uniqueId: "10255",
            firstName: "",
            lastName: "",
            title: "",
            leftTotal: 30,
            rightTotal: 300,
          },

          {
            className: "custom-node",
            businessCenter: "500",
            uniqueId: "01803.1",
            firstName: "Noah",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
    ],
  },

  "BC1-401": {
    className: "custom-node",
    businessCenter: "963.1567",
    uniqueId: "693",
    firstName: "Millad",
    lastName: "dds",
    title: "Director",
    leftTotal: 50,
    rightTotal: 500,
    children: [
      {
        className: "custom-node",
        businessCenter: "742.3562",
        uniqueId: "853",
        firstName: "SOKU",
        lastName: "...",
        title: "Assistant Head",
        leftTotal: 845,
        rightTotal: 951,

        children: [
          {
            className: "custom-node",
            businessCenter: "02.36",
            uniqueId: "582",
            firstName: "Reynolds",
            lastName: "Taylor",
            title: "Assistant Head",
            leftTotal: 971,
            rightTotal: 142,
            children: [
              {
                className: "custom-node",
                uniqueId: "112",
                businessCenter: "632",
                firstName: "Matthews",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 55,
                rightTotal: 36,
                children: [
                  {
                    className: "custom-node",
                    businessCenter: "3233",
                    uniqueId: "93.36",
                    firstName: "Udana",
                    lastName: "Taylor",
                    title: "Assistant ",
                    leftTotal: 55,
                    rightTotal: 36,
                    children: [
                      {
                        className: "custom-node",
                        businessCenter: "78512",
                        uniqueId: "9874",
                        firstName: "Robinson",
                        lastName: "Taylor",
                        title: "Assistant ",
                        leftTotal: 55,
                        rightTotal: 36,
                        children: [
                          {
                            className: "custom-node",
                            businessCenter: "3694254.612",
                            uniqueId: "12589.221",
                            firstName: "Somy",
                            lastName: "Taylor",
                            title: "Assistant ",
                            leftTotal: 55,
                            rightTotal: 36,
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                className: "custom-node",
                businessCenter: "787888",
                uniqueId: "7893.3",
                firstName: "Jenny",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 55,
                rightTotal: 36,
              },
            ],
          },
          {
            className: "custom-node",
            businessCenter: "025810",
            uniqueId: "369.28",
            firstName: "Oliver",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 30,
            rightTotal: 300,
          },
        ],
      },
      {
        className: "custom-node",
        businessCenter: "93.15542",
        uniqueId: "0258.66",
        firstName: "Maku",
        lastName: "Taylor",
        title: "Assistant Head",
        leftTotal: 69,
        rightTotal: 7132,
        children: [
          {
            className: "custom-node",
            businessCenter: "125",
            uniqueId: "999",
            firstName: "Potterrs",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 48,
            rightTotal: 63,
          },
          {
            className: "custom-node",
            businessCenter: "965",
            uniqueId: "777",
            firstName: "Metters",
            lastName: "Taylor",
            title: "Assistant ",
            leftTotal: 48,
            rightTotal: 63,
            children: [
              {
                className: "custom-node",
                businessCenter: "369",
                uniqueId: "30.28",
                firstName: "Dominick",
                lastName: "Taylor",
                title: "Assistant ",
                leftTotal: 48,
                rightTotal: 63,
                children: [
                  {
                    className: "custom-node",
                    businessCenter: "425",
                    uniqueId: "458",
                    firstName: "Gred",
                    lastName: "Taylor",
                    title: "Assistant ",
                    leftTotal: 48,
                    rightTotal: 63,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};

// mockData.js
export const bcData = {
  "BC1-401": [
    {
      center: "10656408.001",
      level: 1,
      name: "George Washington",
      left: 2,
      right: 3,
      title: "BC-1st",
      pc: 5,
    },
    {
      center: "10656408.002",
      level: 1,
      name: "Ben Franklin",
      left: 1,
      right: 4,
      title: "BC-1st",
      pc: 3,
    },
  ],
  "BC2-401": [
    {
      center: "10656409.001",
      level: 1,
      name: "Alexander Hamilton",
      left: 2,
      right: 2,
      title: "BC-2nd",
      pc: 4,
    },
  ],

  "BC2-402": [
    {
      center: "10656409.001",
      level: 1,
      name: "Alexander Hamilton",
      left: 2,
      right: 2,
      title: "BC-2nd",
      pc: 4,
    },
  ],

  "BC2-404": [
    {
      center: "10656409.001",
      level: 1,
      name: "Alexander Hamilton",
      left: 2,
      right: 2,
      title: "BC-2nd",
      pc: 4,
    },
  ],
};

export const optionItems = [
  "% On Auto Order",
  "Address",
  "Address 2",
  "Influencer Count",
  "AO Personal Count",
  "AO Start Date",
  "Application Date",
  "Associate Count",
  "Auto Order Cancel Date",
  "Auto Order Count",
  "Auto Orders On Hold",
  "Business Center Count",
  "Business Center Index",
  "Cancel Date",
  "Cancelled Auto Order",
  "City",
  "Commission Period",
  "Contact Opt In",
  "Country",
  "Currency",
  "Customer Count",
  "Customer Id",
  "Customer Number",
  "Customer Type",
  "Customer With BC Count",
  "Email",
  "Email Address 2",
  "Estimated Auto Order Volume",
  "Estimated CVP Sum",
  "Executive",
  "Executive End Date",
  "Executive Start Date",
  "First Name",
  "First Time Check Earner",
  "Full Name",
  "Highest Title Left",
  "Highest Title Right",
  "Language",
  "Last Check Date",
  "Last Name",
  "Last Purchase Date",
  "Leadership Bonus Date",
  "Mobile",
  "Move up one level",
  "MTD Sponsored",
  "Next Auto Order Cycle",
  "Next Auto Order Date",
  "Not received a check in (X) days",
  "On Auto Order",
  "On Business Accelerator Suite",
  "Original Sponsor",
  "Other Phone",
  "PC Count - Entire Team",
  "PC Count - Personally Sponsored",
  "PC w/ Business Center",
  "Phone Day",
  "Phone Night",
  "Placement",
  "Profile Picture",
  "Qual Date",
  "Renewal Date",
  "Side",
  "Sponsor Customer Id",
  "State/Province",
  "Status",
  "Title",
  "Title Date",
  "Tree Level",
  "Volume Needed",
  "Weeks Since App Date",
  "WTD Sponsored",
  "YTD Sponsored",
  "Zip/Postal Code",
];
